apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: gateway-module-28481
  namespace: MendPerformance
  annotations:
    github.com/project-slug: MendPerformance/gateway-module-28481
spec:
  type: service
  lifecycle: unknown
  owner: mend.io
